# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Calculus-NewtonRaphson
version:      0.1
version_from: NewtonRaphson.pm
installdirs:  site
requires:
    Math::Calculus::Differentiate: 0.3
    Math::Calculus::Expression:    0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
